core/urls.py
from django.urls import path

from .views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

fusion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from stdimage.models import StdImageField


def get_file_path(_instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return filename


class Base(models.Model):
    criado = models.DateField(_('Criação'), auto_now_add=True)
    modificado = models.DateField(_('Atualização'), auto_now=True)
    ativo = models.BooleanField(_('Ativo'), default=True)

    class Meta:
        abstract = True


class Servico(Base):
    ICONE_CHOICES = (
        ('lni-cog', _('Engrenagem')),
        ('lni-stats-up', _('Gráfico')),
        ('lni-users', _('Usuários')),
        ('lni-layers', _('Design')),
        ('lni-mobile', _('Mobile')),
        ('lni-rocket', _('Foguete')),
    )
    servico = models.CharField(_('Serviço'), max_length=100)
    descricao = models.TextField(_('Descrição'), max_length=200)
    icone = models.CharField(_('Icone'), max_length=12, choices=ICONE_CHOICES)

    class Meta:
        verbose_name = _('Serviço')
        verbose_name_plural = _('Serviços')

    def __str__(self):
        return self.servico


class Cargo(Base):
    cargo = models.CharField(_('Cargo'), max_length=100)

    class Meta:
        verbose_name = _('Cargo')
        verbose_name_plural = _('Cargos')

    def __str__(self):
        return self.cargo


class Funcionario(Base):
    nome = models.CharField(_('Nome'), max_length=100)
    cargo = models.ForeignKey('core.Cargo', verbose_name=_('Cargo'), on_delete=models.CASCADE)
    bio = models.TextField(_('Bio'), max_length=200)
    imagem = StdImageField(_('Imagem'), upload_to=get_file_path, variations={
        'thumb': {
            'width': 480,
            'height': 480,
            'crop': True
        }
    })
    facebook = models.CharField('Facebook', max_length=100, default='#')
    twitter = models.CharField('Twitter', max_length=100, default='#')
    instagram = models.CharField('Instagram', max_length=100, default='#')

    class Meta:
        verbose_name = _('Funcionário')
        verbose_name_plural = _('Funcionários')

    def __str__(self):
        return self.nome


class Recurso(Base):
    ICONE_CHOICES = (
        ('lni-rocket', _('Foguete')),
        ('lni-laptop-phone', _('Responsivo')),
        ('lni-cog', _('Engrenagem')),
        ('lni-leaf', _('Folha')),
        ('lni-layers', _('Camadas'))
    )
    nome = models.CharField(_('Nome'), max_length=100)
    icone = models.CharField(_('Icone'), max_length=20, choices=ICONE_CHOICES)
    descricao = models.TextField(_('Descricao'), max_length=100)

    class Meta:
        verbose_name = _('Recurso')
        verbose_name_plural = _('Recursos')

    def __str__(self):
        return self.nome

core/forms.py
from django import forms
from django.core.mail.message import EmailMessage
from django.utils.translation import gettext_lazy as _


class ContatoForm(forms.Form):
    nome = forms.CharField(label=_('Nome'), max_length=100)
    email = forms.EmailField(label=_('E-mail'), max_length=100)
    assunto = forms.CharField(label=_('Assunto'), max_length=100)
    mensagem = forms.CharField(label=_('Mensagem'), widget=forms.Textarea())

    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        assunto = self.cleaned_data['assunto']
        mensagem = self.cleaned_data['mensagem']

        n = _('Nome')
        e = _('E-mail')
        a = _('Assunto')
        m = _('Mensagem')
        conteudo = f'{n}: {nome}\n{e}: {email}\n{a}: {assunto}\n{m}: {mensagem}'

        mail = EmailMessage(
            subject=assunto,
            body=conteudo,
            from_email='contato@admin.com.br',
            to=['contato@admin.com.br', ],
            headers={'Reply-To': email}
        )
        mail.send()

core/views.py
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.translation import gettext as _
from django.utils import translation

from .models import Servico, Funcionario, Recurso
from .forms import ContatoForm


class IndexView(FormView):
    template_name = 'index.html'
    form_class = ContatoForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        lang = translation.get_language()
        context['servicos'] = Servico.objects.order_by('?').all()
        context['funcionarios'] = Funcionario.objects.order_by('?').all()
        recursos = Recurso.objects.order_by('?').all()
        context['recursos_left'] = recursos[0:len(recursos)//2]
        context['recursos_rigth'] = recursos[(len(recursos)//2):]
        context['lang'] = lang
        translation.activate(lang)
        return context

    def form_valid(self, form, *args, **kwargs):
        form.send_mail()
        messages.success(self.request, _('E-mail enviado com sucesso'))
        return super(IndexView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, _('Erro ao enviar e-mail'))
        return super(IndexView, self).form_invalid(form, *args, **kwargs)

core/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Fusion</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <!-- Icon -->
    <link rel="stylesheet" href="{% static '/fonts/line-icons.css' %}">
    <!-- Owl carousel -->
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.theme.css' %}">

    <!-- Animate -->
    <link rel="stylesheet" href="{% static '/css/animate.css' %}">
    <!-- Main Style -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="{% static '/css/responsive.css' %}">

</head>
<body>

<!-- Header Area wrapper Starts -->
<header id="header-wrap">
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-md bg-inverse fixed-top scrolling-navbar">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a href="{% url 'index' %}" class="navbar-brand"><img src="{% static '/img/logo.png' %}" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <i class="lni-menu"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto w-100 justify-content-end clearfix">
                    <li class="nav-item active">
                        <a class="nav-link" href="#hero-area">
                            {% trans 'Inicío' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#services">
                            {% trans 'Serviços' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#team">
                            {% trans 'Equipe' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#pricing">
                            {% trans 'Preços' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#testimonial">
                            {% trans 'Clientes' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">
                            {% trans 'Contato' %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->
{% block content %}{% endblock %}

<!-- Go to Top Link -->
<a href="#" class="back-to-top">
    <i class="lni-arrow-up"></i>
</a>

<!-- Preloader -->
<div id="preloader">
    <div class="loader" id="loader-1"></div>
</div>
<!-- End Preloader -->

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static '/js/jquery-min.js' %}"></script>
<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static '/js/owl.carousel.min.js' %}"></script>
<script src="{% static '/js/wow.js' %}"></script>
<script src="{% static '/js/jquery.nav.js' %}"></script>
<script src="{% static '/js/scrolling-nav.js' %}"></script>
<script src="{% static '/js/jquery.easing.min.js' %}"></script>
<script src="{% static '/js/main.js' %}"></script>
<script src="{% static '/js/form-validator.min.js' %}"></script>
<script src="{% static '/js/contact-form-script.min.js' %}"></script>

</body>
</html>

core/templates/chamada.html
{% load static %}

<section id="cta" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12 wow fadeInLeft" data-wow-delay="0.3s">
                <div class="cta-text">
                    <h4>Get 30 days free trial</h4>
                    <p>Praesent imperdiet, tellus et euismod euismod, risus lorem euismod erat, at finibus neque odio
                        quis metus. Donec vulputate arcu quam. </p>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-xs-12 text-right wow fadeInRight" data-wow-delay="0.3s">
                </br><a href="#" class="btn btn-common">Register Now</a>
            </div>
        </div>
    </div>
</section>

core/templates/clientes.html
{% load static %}

<section id="testimonial" class="testimonial section-padding">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div id="testimonials" class="owl-carousel wow fadeInUp" data-wow-delay="1.2s">
                    <div class="item">
                        <div class="testimonial-item">
                            <div class="img-thumb">
                                <img src="{% static '/img/testimonial/img1.jpg' %}" alt="">
                            </div>
                            <div class="info">
                                <h2><a href="#">David Smith</a></h2>
                                <h3><a href="#">Creative Head</a></h3>
                            </div>
                            <div class="content">
                                <p class="description">Praesent cursus nulla non arcu tempor, ut egestas elit tempus. In
                                    ac ex fermentum, gravida felis nec, tincidunt ligula.</p>
                                <div class="star-icon mt-3">
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimonial-item">
                            <div class="img-thumb">
                                <img src="{% static '/img/testimonial/img2.jpg' %}" alt="">
                            </div>
                            <div class="info">
                                <h2><a href="#">Domeni GEsson</a></h2>
                                <h3><a href="#">Awesome Technology co.</a></h3>
                            </div>
                            <div class="content">
                                <p class="description">Praesent cursus nulla non arcu tempor, ut egestas elit tempus. In
                                    ac ex fermentum, gravida felis nec, tincidunt ligula.</p>
                                <div class="star-icon mt-3">
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimonial-item">
                            <div class="img-thumb">
                                <img src="{% static '/img/testimonial/img3.jpg' %}" alt="">
                            </div>
                            <div class="info">
                                <h2><a href="#">Dommini Albert</a></h2>
                                <h3><a href="#">Nesnal Design co.</a></h3>
                            </div>
                            <div class="content">
                                <p class="description">Praesent cursus nulla non arcu tempor, ut egestas elit tempus. In
                                    ac ex fermentum, gravida felis nec, tincidunt ligula.</p>
                                <div class="star-icon mt-3">
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimonial-item">
                            <div class="img-thumb">
                                <img src="{% static '/img/testimonial/img4.jpg' %}" alt="">
                            </div>
                            <div class="info">
                                <h2><a href="#">Fernanda Anaya</a></h2>
                                <h3><a href="#">Developer</a></h3>
                            </div>
                            <div class="content">
                                <p class="description">Praesent cursus nulla non arcu tempor, ut egestas elit tempus. In
                                    ac ex fermentum, gravida felis nec, tincidunt ligula.</p>
                                <div class="star-icon mt-3">
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-filled"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                    <span><i class="lni-star-half"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/contato.html
{% load static %}

<section id="contact" class="section-padding bg-gray">
    <div class="container">
        <div class="section-header text-center">
            <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Contate-nos</h2>
            <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row contact-form-area wow fadeInUp" data-wow-delay="0.3s">
            <div class="col-lg-7 col-md-12 col-sm-12">
                <div class="contact-block">
                    <form id="contato" method="post" action="{% url 'index' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="id_nome" name="nome" placeholder="Nome"
                                           required data-error="Please enter your name" maxlength="100">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" placeholder="E-mail" id="id_email" class="form-control" name="email"
                                           required data-error="Please enter your email">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="text" placeholder="Assunto" id="id_assunto" name="assunto" class="form-control"
                                           required data-error="Please enter your subject">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea class="form-control" id="id_mensagem" placeholder="Mensagem" name="mensagem" rows="7"
                                              data-error="Write your message" required></textarea>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="submit-button text-left">
                                    <button class="btn btn-common" id="form-submit" type="submit">Enviar e-mail</button>
                                    <div id="msgSubmit" class="h3 text-center hidden"></div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 col-md-12 col-xs-12">
                <div class="map">
                    <object style="border:0; height: 280px; width: 100%;"
                            data="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d34015.943594576835!2d-106.43242624069771!3d31.677719472407432!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e75d90e99d597b%3A0x6cd3eb9a9fcd23f1!2sCourtyard+by+Marriott+Ciudad+Juarez!5e0!3m2!1sen!2sbd!4v1533791187584"></object>
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/equipe.html
{% load static %}

<section id="team" class="section-padding bg-gray">
    <div class="container">
        <div class="section-header text-center">
            <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Conheça nossa equipe</h2>
            <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row">
            {% for f in funcionarios %}
            <div class="col-lg-6 col-md-12 col-xs-12">
                <!-- Team Item Starts -->
                <div class="team-item wow fadeInRight" data-wow-delay="0.2s">
                    <div class="team-img">
                        <img class="img-fluid" src="{{ f.imagem.thumb.url }}" alt="{{ f.nome }}">
                    </div>
                    <div class="contetn">
                        <div class="info-text">
                            <h3><a href="#">{{ f.nome }}</a></h3>
                            <p>{{ f.cargo }}</p>
                        </div>
                        <p>{{ f.bio }}</p>
                        <ul class="social-icons">
                            <li><a href="{{ f.facebook }}"><i class="lni-facebook-filled" aria-hidden="true"></i></a></li>
                            <li><a href="{{ f.twitter }}"><i class="lni-twitter-filled" aria-hidden="true"></i></a></li>
                            <li><a href="{{ f.instagram }}"><i class="lni-instagram-filled" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
                <!-- Team Item Ends -->
            </div>
            {% endfor %}

        </div>
    </div>
</section>

core/templates/features.html
{% load static %}

<section id="features" class="section-padding">
    <div class="container">
        <div class="section-header text-center">
            <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Awesome Features</h2>
            <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="content-left">
                    {% for r in recursos_left %}
                    <div class="box-item wow fadeInLeft" data-wow-delay="0.1s">
                <span class="icon">
                  <i class="{{ r.icone}}"></i>
                </span>
                        <div class="text">
                            <h4>{{ r.nome }}</h4>
                            <p>{{ r.descricao }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="show-box wow fadeInUp" data-wow-delay="0.3s">
                    <img src="{% static '/img/feature/intro-mobile.png' %}" alt="">
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="content-right">
                    {% for r in recursos_rigth %}
                    <div class="box-item wow fadeInLeft" data-wow-delay="0.1s">
                <span class="icon">
                  <i class="{{ r.icone}}"></i>
                </span>
                        <div class="text">
                            <h4>{{ r.nome }}</h4>
                            <p>{{ r.descricao }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/footer.html
{% load static %}

<footer id="footer" class="footer-area section-padding">
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
                    <div class="widget">
                        <h3 class="footer-logo"><img src="{% static '/img/logo.png' %}" alt=""></h3>
                        <div class="textwidget">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lobortis tincidunt est,
                                et euismod purus suscipit quis.</p>
                        </div>
                        <div class="social-icon">
                            <a class="facebook" href="#"><i class="lni-facebook-filled"></i></a>
                            <a class="twitter" href="#"><i class="lni-twitter-filled"></i></a>
                            <a class="instagram" href="#"><i class="lni-instagram-filled"></i></a>
                            <a class="linkedin" href="#"><i class="lni-linkedin-filled"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                    <h3 class="footer-titel">Products</h3>
                    <ul class="footer-link">
                        <li><a href="#">Tracking</a></li>
                        <li><a href="#">Application</a></li>
                        <li><a href="#">Resource Planning</a></li>
                        <li><a href="#">Enterprise</a></li>
                        <li><a href="#">Employee Management</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                    <h3 class="footer-titel">Resources</h3>
                    <ul class="footer-link">
                        <li><a href="#">Payment Options</a></li>
                        <li><a href="#">Fee Schedule</a></li>
                        <li><a href="#">Getting Started</a></li>
                        <li><a href="#">Identity Verification</a></li>
                        <li><a href="#">Card Verification</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                    <h3 class="footer-titel">Contact</h3>
                    <ul class="address">
                        <li>
                            <a href="#"><i class="lni-map-marker"></i> 105 Madison Avenue - <br> Third Floor New York,
                                NY 10016</a>
                        </li>
                        <li>
                            <a href="#"><i class="lni-phone-handset"></i> P: +84 846 250 592</a>
                        </li>
                        <li>
                            <a href="#"><i class="lni-envelope"></i> E: contact@uideck.com</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright-content">
                        <p>Copyright © 2020 <a rel="nofollow" href="https://uideck.com">UIdeck</a> All Right Reserved
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

core/templates/hero.html
{% load static %}
{% load i18n %}

<div id="hero-area" class="hero-area-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-12 col-sm-12 col-xs-12">
                <div class="contents">
                    <h2 class="head-title">{% trans 'Com a' %}<br>{% trans 'Fusion' %}</h2>
                    <p>{% trans 'Você irá mais longe!' %}</p>
                    <div class="header-button">
                        <a href="#" class="btn btn-common">{% trans 'Saiba mais' %}</i></a>
                        <a href="#" class="btn btn-border video-popup">{% trans 'Entre em contato' %}</i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
                <div class="intro-img">
                    <img class="img-fluid" src="{% static '/img/intro-mobile.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    {% if messages %}
    {% for m in messages %}
    <div class="alert alert-{{ messages.tags}}">
        <button type="button" class="close" data-dismiss="alert"></button>
        <strong>{{ m }}</strong>
    </div>
    {% endfor %}
    {% endif %}
</div>
</header>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Hero Area Start -->
{% include 'hero.html' %}
<!-- Hero Area End -->

<!-- Services Section Start -->
{% include 'servicos.html' %}
<!-- Services Section End -->

<!-- About Section start -->
{% include 'sobre.html' %}
<!-- About Section End -->

<!-- Features Section Start -->
{% include 'features.html' %}
<!-- Features Section End -->

<!-- Team Section Start -->
{% include 'equipe.html' %}
<!-- Team Section End -->

<!-- Pricing section Start -->
{% include 'precos.html' %}
<!-- Pricing Table Section End -->

<!-- Testimonial Section Start -->
{% include 'clientes.html' %}
<!-- Testimonial Section End -->

<!-- Call To Action Section Start -->
{% include 'chamada.html' %}
<!-- Call To Action Section Start -->

<!-- Contact Section Start -->
{% include 'contato.html' %}
<!-- Contact Section End -->

<!-- Footer Section Start -->
{% include 'footer.html' %}
<!-- Footer Section End -->

{% endblock %}

core/templates/servicos.html
{% load static %}

<section id="services" class="section-padding">
    <div class="container">
        <div class="section-header text-center">
            <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Nossos Serviços</h2>
            <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row">
            {% for s in servicos %}
            <!-- Services item -->
            <div class="col-md-6 col-lg-4 col-xs-12">
                <div class="services-item wow fadeInRight" data-wow-delay="0.3s">
                    <div class="icon">
                        <i class="{{ s.icone }}"></i>
                    </div>
                    <div class="services-content">
                        <h3><a href="#">{{ s.servico }}</a></h3>
                        <p>{{ s.descricao }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>